### ISSUE TITLE
基于Docker安装的环境无法切换源

### ISSUE THREAD

**Issue by ImHeroZero** [yoimiya-kokomi/Yunzai-Bot#13]
如题,我哭死/(ㄒoㄒ)/~~
docker安装锁定的git的下载地址,无法 切换y佬的源

**Comment by SirlyDreamer** [comment]
> 如题,我哭死/(ㄒoㄒ)/~~ docker安装锁定的git的下载地址,无法 切换y佬的源

源镜像在7月6日已经切换成喵喵的源了，请使用`docker compose pull`更新镜像

另外，你可以使用`docker exec -it yunzai-bot /bin/sh`进入容器，运行切换仓库的命令，此后操作和linux相同

**Comment by ImHeroZero** [comment]
> > 如题,我哭死/(ㄒoㄒ)/~~ docker安装锁定的git的下载地址,无法 切换y佬的源
> 
> 源镜像在7月6日已经切换成喵喵的源了，请使用`docker compose pull`更新镜像
> 
> 另外，你可以使用`docker exec -it yunzai-bot /bin/sh`进入容器，运行切换仓库的命令，此后操作和linux相同

谢谢,docker我不大懂(完全)
