### ISSUE TITLE
#角色 只能显示9个角色

### ISSUE THREAD

**Issue by keaiye** [yoimiya-kokomi/Yunzai-Bot#16]
绑定cookie后只能显示9个角色，不显示全部了

**Comment by bling-yshs** [comment]
config.js可改
`  roleAllAvatar: false, // #角色 命令下是否展示全部角色 true：展示全部角色，false：展示12个角色，默认false`

**Comment by keaiye** [comment]
> config.js可改 ` roleAllAvatar: false, // #角色 命令下是否展示全部角色 true：展示全部角色，false：展示12个角色，默认false`

ok

**Comment by keaiye** [comment]
> config.js可改 ` roleAllAvatar: false, // #角色 命令下是否展示全部角色 true：展示全部角色，false：展示12个角色，默认false`

ok
