### ISSUE TITLE
#角色统计

### ISSUE THREAD

**Issue by RockRadix** [yoimiya-kokomi/Yunzai-Bot#18]
#角色记录，正常。但角色统计缺少最新的2.8万叶卡池统计，在上一个卡池断开
![0f2700b8a5e7dccc1a8697f1cb04f6a7](https://user-images.githubusercontent.com/99504275/180131402-f4ac558b-896b-4d6e-b6ed-cea27658e719.jpg)
![dda4ef66af4c00af6e29eef67ee53613](https://user-images.githubusercontent.com/99504275/180131412-6b0bc72a-161b-4a63-acbe-30f5e9d15fd6.jpg)
![image](https://user-images.githubusercontent.com/99504275/180131434-cce58d0d-fe65-4464-b96d-9202a5dd1674.png)
。

**Comment by yoimiya-kokomi** [comment]
更新到最新版即可
