### ISSUE TITLE
米游社签到报错

### ISSUE THREAD

**Issue by Shvamp** [yoimiya-kokomi/Yunzai-Bot#25]
米游社签到：invalid request

**Comment by AkiraShe** [comment]
遇到同样问题了。另外请问如何暂停bot上所有用户的自动签到？

**Comment by FQrabbit** [comment]
salt和随机数格式好像改了

**Comment by Maolaohei** [comment]
可以签到了
![Uploading Screenshot_2022-08-05-10-15-07-482_com.tencent.mobileqq-edit.jpg…]()

**Comment by magic5al** [comment]
> 米游社签到：invalid request

更新云崽就行了，已经修复了

**Comment by AkiraShe** [comment]
> > 米游社签到：invalid request
> 
> 更新云崽就行了，已经修复了

更新后正常了，感谢。

**Comment by FQrabbit** [comment]
> > > 米游社签到：invalid request
> > 
> > 
> > 更新云崽就行了，已经修复了
> 
> 更新后正常了，感谢。

你查询uid有无问题 @AkiraShe
