### ISSUE TITLE
米游社签到时提示签到: [登录失效，请重新登录]，但读帖分享成功

### ISSUE THREAD

**Issue by yutouyes** [yoimiya-kokomi/Yunzai-Bot#27]
根据教程https://github.com/yoimiya-kokomi/Yunzai-Bot/blob/master/resources/readme/%E5%91%BD%E4%BB%A4%E8%AF%B4%E6%98%8E.md#%E5%A6%82%E4%BD%95%E8%8E%B7%E5%8F%96%E7%B1%B3%E6%B8%B8%E7%A4%BE-cookie 在米游社获取的cookie，绑定后签到没有完全成功按提示重新登录重新绑定cookie后报错相同
![image](https://user-images.githubusercontent.com/17039457/183261112-62f52390-dd2c-47ec-8331-b2705bf18a0a.png)

在米哈游通行证下获取cookie，cookie内容多一些，但是报错也一样
![image](https://user-images.githubusercontent.com/17039457/183261161-ed07b93b-ce23-4794-b978-25231e7b5b0f.png)

云崽版本是2.2.1
![74d3bba16eca553638c0fda7cb94d0db](https://user-images.githubusercontent.com/17039457/183261166-1bbf72ae-8f6d-4684-bf19-a01c723a803c.jpg)

而且奇怪的是只有一个账号有这个问题，其他的都正常签到

**Comment by ctrlcvs** [comment]
login_ticket只有30分钟内有效这个在文档也有说明，如果不触发会失效，触发指令后才会保存stoken到文件中进行查询，不过目前最新版本图鉴加了未登录的拦截。
