### ISSUE TITLE
关于生成图片偶尔会出现文字消失的问题讨论

### ISSUE THREAD

**Issue by sjlei** [yoimiya-kokomi/Yunzai-Bot#28]
# 问题描述

复现概率极低，偶尔会出现下图的情况，样式都没问题，只有文字消失了。
![image](https://user-images.githubusercontent.com/34293221/183802608-a2b71e3e-80d7-4fb4-a5d3-5081d1101787.png)

# 问题原因
通过生成后的html文件打开DevTools调试后发现，字体在Network面板中显示为`CORS error`，很有可能就是这个原因导致的。
![image](https://user-images.githubusercontent.com/34293221/183803533-9763bb93-cb84-489f-903e-e1676d52d634.png)

查看源码发现，字体预加载语句上加上了`crossorigin`跨域标记，经测试由于是本地字体文件，不通过http协议访问，所以不需要加此标记，去掉后就正常了。
![image](https://user-images.githubusercontent.com/34293221/183805808-88f3ca0c-c654-4c66-a7fc-809553c509db.png)

去掉之后：
![image](https://user-images.githubusercontent.com/34293221/183806840-11818572-c2f8-49dc-a5fd-daf82bc8545f.png)
![image](https://user-images.githubusercontent.com/34293221/183806810-918d5934-f62e-4622-bf6c-cf75bcb22955.png)

# 后续测试

## 测试环境

1. 模拟慢速电脑，后台开启编译打包其他项目，占用CPU资源。
![image](https://user-images.githubusercontent.com/34293221/183807030-6e1f5b28-7ee7-445a-b61c-f4874eecfb79.png)
2. 渲染函数修改，直接生成到本地图片，并去掉 sleep
![image](https://user-images.githubusercontent.com/34293221/183807331-5a33a61f-6cb3-48f0-b20d-b807b875a538.png)
3. 测试方法如下，生成1000张图片
![image](https://user-images.githubusercontent.com/34293221/183807373-afd85c85-e441-43e3-8a91-9d5c49d63626.png)

## 测试：保留`crossorigin`
结果：生成1000张图片，有4张是生成错误的（这在1核1G的服务器上可能会更多）
![02_10_110140](https://user-images.githubusercontent.com/34293221/183807595-16683b62-e96d-4a4d-bacf-e4dafb6b96dd.png)
![02_10_110102](https://user-images.githubusercontent.com/34293221/183807581-fa4211e1-2e41-45fa-b426-b682e9178997.png)
![02_10_110114](https://user-images.githubusercontent.com/34293221/183807586-c3ba4c7e-8a46-4a93-b6f9-4b4a37f464fd.png)
![02_10_110127](https://user-images.githubusercontent.com/34293221/183807592-5901c4fd-5273-4d5d-9922-ce8955d41ae7.png)

## 测试：删除`crossorigin`
结果：生成了2000张图片，全部测试通过。
![image](https://user-images.githubusercontent.com/34293221/183807807-089bc31f-d934-48ee-84f9-dde39001e442.png)

---------------

@yoimiya-kokomi 喵佬你也可以尝试测试一下，确认就是此问题之后，就可以这么修改了，这将能彻底解决图片生成文字消失的问题。

**Comment by yoimiya-kokomi** [comment]
多谢，已经更新至最新版miao-plugin～
