### ISSUE TITLE
米游币签到API好像又换了

### ISSUE THREAD

**Issue by ayakasuki** [yoimiya-kokomi/Yunzai-Bot#38]
#米游社原神签到 任务获得米游币那个 今天好像其他插件api也换了，现在这个命令以后米游社任务没变化来着

**Comment by ctrlcvs** [comment]
> #米游社原神签到 任务获得米游币那个 今天好像其他插件api也换了，现在这个命令以后米游社任务没变化来着

并没有换接口，只是浏览帖子加了验证码而已，而且验证码比签到的更高级，目前没有解决方法
